---
abstract: 'Unofficial asynchronous API for Elasticsearch using callbacks'
author:
  - 'Denis Ibaev <dionys@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-Elasticsearch-Async-Simple
no_index:
  directory:
    - t
    - inc
    - t
requires:
  AnyEvent::HTTP: 0
  Module::Runtime: 0
  Moo: 0
  Package::Stash: 0
  Search::Elasticsearch: 1.10
  Time::HiRes: 0
  namespace::clean: 0
  perl: 5.008000
resources:
  bugtracker: http://github.com/dionys/search-elasticsearch-async/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dionys/search-elasticsearch-async
version: 0.03
